image: node:12.16.1

stages:
  - build
  - deploy

Build:
  stage: build
  tags:
    - beekast
    - kubernetes
    - compute
    - front
  before_script: 
    - yarn install
  script:
    - export NODE_OPTIONS=--max_old_space_size=4096
    - yarn build

