
stages:
  - artifact
  - container
  - deploy

artifact:
  stage: artifact
  image: node:12.16.1
  tags:
    - beekast
    - kubernetes
    - compute
    - front
  before_script: 
    - yarn install
  script:
    - yarn build
  artifacts:
    name: 'inspiration'
    paths:
      - dist
  only:
    refs:
      - /^master$/
    changes:
      - app/**/*
      - helm/**/*
      - gitlab-ci/**/*

container:
  stage: container
  image: 809772074319.dkr.ecr.eu-west-1.amazonaws.com/build/docker-aws-cli:latest
  tags:
    - beekast
    - kubernetes
    - compute
    - default
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - aws ecr list-images --repository-name beekast-inspirations --region eu-west-1
  script:
    - find / -iname "dist"
    - docker pull beekast-inspirations || true
    - docker build -t beekast-inspirations -f beekast-inspirations.Dockerfile .
    - docker tag beekast-inspirations:latest 809772074319.dkr.ecr.eu-west-1.amazonaws.com/beekast-inspirations:latest
    - docker push 809772074319.dkr.ecr.eu-west-1.amazonaws.com/beekast-inspirations:latest 
  only:
    refs:
      - /^master$/
    changes:
      - app/**/*
      - helm/**/*
      - gitlab-ci/**/*

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:2.16.1
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.compute.beekast.com
  before_script:
    - helm init -c
    - echo $CI_COMMIT_REF_SLUG
  script:
    - helm upgrade inspirations ./helm/inspirations --recreate-pods --wait --timeout 600 --namespace inspirations
  only:
    refs:
      - /^master$/
    changes:
      - app/**/*
      - helm/**/*
      - gitlab-ci/**/*
